const listaProdutos = [
  
    {
      idproduto: 1,
      id_categoria: 1,
      descricao: "Geladeira Brastemp Frost Free Side Inverse 540 litros",
      preco: 6389,
      precofinal: 5019,
      imagem: "./imagens/geladeira1.jpeg",
      categoria: "Geladeira",
    },
    {
      idproduto: 2,
      id_categoria: 1,
      descricao: "Geladeira Brastemp Branca Frost Free 375 litros",
      preco: 2068,
      precofinal: 1910.9,
      imagem: "./imagens/geladeira2.jpeg",
      categoria: "Geladeira",
    },
    {
      idproduto: 3,
      id_categoria: 1,
      descricao: "Geladeira Frost Free Consul Prata 340 litros",
      preco: 2199,
      precofinal: 2069,
      imagem: "./imagens/geladeira3.jpeg",
      categoria: "Geladeira",
    },
    {
      idproduto: 4,
      id_categoria: 2,
      descricao: "Fogão 4 Bocas Consul Inox com Mesa de Vidro",
      preco: 1209,
      precofinal: 1129,
      imagem: "./imagens/fogao1.jpeg",
      categoria: "Fogão",
    },
    {
      idproduto: 5,
      id_categoria: 2,
      descricao:
        "Fogão de Piso 4 Bocas Atlas Monaco com Acendimento Automático",
      preco: 600,
      precofinal: 519.7,
      imagem: "./imagens/fogao2.jpeg",
      categoria: "Fogão",
    },
    {
      idproduto: 6,
      id_categoria: 3,
      descricao: "Micro-ondas Consul 32 litros Inox 220V",
      preco: 580,
      precofinal: 409.88,
      imagem: "./imagens/microondas01.jpeg",
      categoria: "Micro-ondas",
    },
    {
      idproduto: 7,
      id_categoria: 3,
      descricao: "Micro-ondas 25L Espelhado Philco 220V",
      preco: 508.7,
      precofinal: 464.53,
      imagem: "./imagens/microondas02.jpeg",
      categoria: "Micro-ondas",
    },
    {
      idproduto: 8,
      id_categoria: 3,
      descricao: "Micro-ondas Electrolux 20L Branco",
      preco: 459,
      precofinal: 436.05,
      imagem: "./imagens/microondas03.jpeg",
      categoria: "Micro-ondas",
    },
    {
      idproduto: 9,
      id_categoria: 4,
      descricao:
        "Lava-Louça Electroclux Inox com 10 Serviços, 6 Programas de Lavagem",
      preco: 3500,
      precofinal: 2799.9,
      imagem: "./imagens/lavalouca1.jpeg",
      categoria: "Lava-louças",
    },
    {
      idproduto: 10,
      id_categoria: 4,
      descricao: "Lava-Louça Compacta com 8 Serviços Branca 127V Brastemp",
      preco: 1970.5,
      precofinal: 1730.61,
      imagem: "./imagens/lavalouca2.jpeg",
      categoria: "Lava-louças",
    },
    {
      idproduto: 11,
      id_categoria: 5,
      descricao:
        "Lavadora de Roupas Brastemp 11 kg com Turbo Performance Branca",
      preco: 1690,
      precofinal: 1214.1,
      imagem: "./imagens/lavadoraderoupas1.jpeg",
      categoria: "Lavadora",
    },
    {
      idproduto: 12,
      id_categoria: 5,
      descricao: "Lavadora de Roupas Philco Inverter 12 kg",
      preco: 2399,
      precofinal: 2179.9,
      imagem: "./imagens/lavadoraderoupas2.jpeg",
      categoria: "Lavadora",
    },
  ];

export default listaProdutos;
